[server]
redirect_url = "http://localhost:4000/"
base_url = "http://localhost:4000"
secure_sessions = false
bot.enabled = true

[cdn]
service = "s3"
base_url = "https://duelchannel-replays-bucket.s3.us-east-2.amazonaws.com"
bucket = "duelchannel-replays-bucket"
region = "us-east-2"

[mmr]
matches_until_rated = 10

[mmr.model.glicko2]
period = "24h"

[http]
port = 4000

[awards.beta_challenger]
threshold = 16300

[rank.x]
threshold = 22300
[rank.ss]
threshold = 19000
[rank.s]
threshold = 16300
[rank.aa]
threshold = 14000
[rank.a]
threshold = 11200
[rank.b]
threshold = 8300
