[server]
redirect_url = "http://localhost:4000/"
base_url = "http://localhost:4000"
secure_sessions = false
bot.enabled = true

[cdn]
service = "s3"
base_url = "https://duelchannel-replays-bucket.s3.us-east-2.amazonaws.com"
bucket = "duelchannel-replays-bucket"
region = "us-east-2"

[mmr]
model = "openskill"
command = "uv run main.py"
tau = 0.08333333333
defaults.rating = 25
defaults.deviation = 8.333333333333

[http]
port = 4000
